stages:
  
build
push
deploy

variables:
  IMAGE: "registry.gitlab.com/USERNAME/my-app"
  KUBE_NAMESPACE: "default"

before_script:
  
echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

1️⃣ BUILD: Docker-Image erstellen
build:
  stage: build
  script:
    
docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA .
only:
main

2️⃣ PUSH: Image in die Registry hochladen
push:
  stage: push
  script:
    
docker push $IMAGE:$CI_COMMIT_SHORT_SHA
only:
main

3️⃣ DEPLOY: Kubernetes Deployment aktualisieren
deploy:
  stage: deploy
  script:
    helm upgrade --install my-app helm/ --set image.tag=$CI_COMMIT_SHORT_SHA
only:
main
