apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        
name: my-app
        image: registry.gitlab.com/USERNAME/my-app:latest
        ports:
containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
    
port: 80
    targetPort: 5000
selector:
  app: my-app
